# Use an official Python image as a base
FROM python:3.12-slim

# revisit using alpine base image to reduce image size
# FROM python:3.13-alpine
# FROM python:3.12-alpine
# Install dependencies
# RUN apk add --no-cache g++ gcc musl-dev libffi-dev openssl-dev

RUN apt-get update && apt-get install build-essential -y

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

RUN pip install --upgrade pip

# Install the dependencies
RUN pip install -r requirements.txt

# Copy the application code
COPY . .

# Run the command to start the app when the container launches
CMD ["python", "app/data_ingestion.py"]