name: Build and Deploy LOLA HR SLACK FASTAPI

on:
  push:
    branches:
      - main

env:
  CI_COMMIT_REF_SLUG_PROD: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      #  Pend this till when testing is implemented
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Test build
      #   run: |
      #     pip install .
      #     python -c "import lola; print(lola.__version__)"

      - name: Print version
        run: |
          echo "Build version: " ${{ env.CI_COMMIT_REF_SLUG_PROD }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/lola-hr:latest

      - name: Set up ArgoCD CLI
        # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging'
        run: |
          sudo curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo chmod +x /usr/local/bin/argocd
    
      - name: ArgoCD Login and Sync
        # if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging'
        run: |
          APP_NAME="lola-hr-slack-fast-api"
          yes | argocd login ${{ vars.ARGOCD_STAGING_URL }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
          argocd app actions run $APP_NAME restart --kind Deployment
     
  # slack-notify:
  #   needs: [ build-and-deploy ]
  #   uses: Helium-Health/.github/.github/workflows/slack-notification-global.yaml@main
  #   secrets: inherit